# -*- coding: utf-8 -*-
"""2318043_TubesDL_CUACA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s7jqL3Nl44GP9NQLy75VfwIshYuiOW8t
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import requests
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping

# Mengambil contoh data polusi Jakarta (Dataset publik harian)
# Kita gunakan data dummy yang strukturnya sama dengan dataset Kaggle Jakarta Air Quality
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pollution.csv"
df = pd.read_csv(url)

# Kita fokus pada kolom polusi (pm2.5)
# Jika menggunakan dataset Kaggle Jakarta, ganti nama kolom sesuai file .csv-nya
df = df[['pm2.5']].rename(columns={'pm2.5': 'pm25'})
df = df.fillna(method='ffill') # Mengisi data kosong

print("Lima data pertama:")
print(df.head())

# Sinkronisasi skala data (0 sampai 1)
scaler = MinMaxScaler(feature_range=(0, 1))
scaled_data = scaler.fit_transform(df)

# Fungsi untuk membuat dataset untuk LSTM
def create_sequences(data, window_size):
    X, y = [], []
    for i in range(len(data) - window_size):
        X.append(data[i:(i + window_size), 0])
        y.append(data[i + window_size, 0])
    return np.array(X), np.array(y)

# Menggunakan 24 jam sebelumnya untuk memprediksi 1 jam ke depan
WINDOW_SIZE = 24
X, y = create_sequences(scaled_data, WINDOW_SIZE)

# Split data (80% Train, 20% Test)
split = int(len(X) * 0.8)
X_train, X_test = X[:split], X[split:]
y_train, y_test = y[:split], y[split:]

# Reshape untuk LSTM [samples, time steps, features]
X_train = X_train.reshape(X_train.shape[0], X_train.shape[1], 1)
X_test = X_test.reshape(X_test.shape[0], X_test.shape[1], 1)

model = Sequential([
    LSTM(64, return_sequences=True, input_shape=(WINDOW_SIZE, 1)),
    Dropout(0.2),
    LSTM(32, return_sequences=False),
    Dropout(0.2),
    Dense(16, activation='relu'),
    Dense(1) # Output prediksi angka polusi
])

model.compile(optimizer='adam', loss='mse')

# Berhenti jika model sudah tidak membaik (mencegah overfitting)
early_stop = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

print("Memulai Training...")
history = model.fit(
    X_train, y_train,
    epochs=20,
    batch_size=32,
    validation_data=(X_test, y_test),
    callbacks=[early_stop],
    verbose=1
)

# Prediksi
predictions = model.predict(X_test)
predictions = scaler.inverse_transform(predictions) # Kembalikan ke angka asli
y_test_actual = scaler.inverse_transform(y_test.reshape(-1, 1))

# Plot Hasil
plt.figure(figsize=(15, 6))
plt.plot(y_test_actual[:200], label='Kualitas Udara Aktual (PM2.5)', color='blue')
plt.plot(predictions[:200], label='Prediksi Model LSTM', color='red', linestyle='--')
plt.title('Prediksi Kualitas Udara Jakarta (PM2.5)')
plt.xlabel('Waktu (Jam)')
plt.ylabel('Konsentrasi Polutan')
plt.legend()
plt.grid(True)
plt.show()

